# dev enviroment


services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: tyler
      MYSQL_ROOT_PASSWORD: abc@123
      MYSQL_DATABASE: engineer-country
      MYSQL_PASSWORD: abc@123
    volumes:
      - db_data:/var/lib/mysql
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/2.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: abc@123
      MYSQL_USER: tyler
      MYSQL_PASSWORD: abc@123
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight:/data
 
volumes:
  db_data:
  redis-data:
  redis_insight: