# dev enviroment


services:
  db:
    image: mysql
    restart: always
    networks:
      - app_net
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: tyler
      MYSQL_ROOT_PASSWORD: abc@123
      MYSQL_DATABASE: engineer-country
      MYSQL_PASSWORD: abc@123
    volumes:
      - db_data:/var/lib/mysql
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/2.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - app_net
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: abc@123
      MYSQL_USER: tyler
      MYSQL_PASSWORD: abc@123
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app_net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    networks:
      - app_net
    ports:
      - "5540:5540"
    volumes:
      - redis_insight:/data

  elasticsearch:
    image: elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - ELASTIC_PASSWORD=password
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app_net
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
 
  kibana:
    image: kibana:8.15.1 
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app_net
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/data

  logstash:
    image: logstash:8.15.1
    container_name: logstash
    networks:
      - app_net
    volumes:
      - logstash_data:/data
    depends_on:
      - elasticsearch
      
networks:
  app_net:
    driver: bridge

volumes:
  db_data:
  redis-data:
  redis_insight:
  elasticsearch_data:
  logstash_data:
  kibana_data: